import Foundation

/// Fixed mood vocabulary — the single source of truth for score. Identifiers are
/// permanent (stored in SwiftData and sent to the LLM as a closed list of choices),
/// so raw values must never be renamed once shipped. `score` is looked up here, never
/// generated by AI, so the same tag always aggregates the same way whether it came
/// from classification or a manual tap.
public enum MoodTag: String, CaseIterable, Codable, Sendable {
    case lovestruck
    case proud
    case happy
    case productive
    case social
    case neutral
    case busyMeetings
    case tired
    case anxious
    case stressed
    case disappointed

    public var score: Int {
        switch self {
        case .lovestruck, .proud: return 2
        case .happy, .productive, .social: return 1
        case .neutral: return 0
        case .busyMeetings, .tired, .anxious: return -1
        case .stressed, .disappointed: return -2
        }
    }

    public var emoji: String {
        switch self {
        case .lovestruck: return "🥰"
        case .proud: return "🤩"
        case .happy: return "😊"
        case .productive: return "💪"
        case .social: return "🎉"
        case .neutral: return "😐"
        case .busyMeetings: return "😵‍💫"
        case .tired: return "😴"
        case .anxious: return "😰"
        case .stressed: return "😣"
        case .disappointed: return "😞"
        }
    }

    /// Plain string for now — matches the rest of the app (no String Catalog yet).
    /// Decoupled from `rawValue` intentionally, so this can move to localization later
    /// without touching the persisted identifier.
    public var displayName: String {
        switch self {
        case .lovestruck: return "Lovestruck"
        case .proud: return "Proud"
        case .happy: return "Happy"
        case .productive: return "Productive"
        case .social: return "Social"
        case .neutral: return "Neutral"
        case .busyMeetings: return "Busy meetings"
        case .tired: return "Tired"
        case .anxious: return "Anxious"
        case .stressed: return "Stressed"
        case .disappointed: return "Disappointed"
        }
    }

    /// Maps a model-produced tag string onto `MoodTag`. Prefers exact `rawValue` match;
    /// also accepts case-insensitive and common display-name variants so a constrained
    /// decode edge case does not silently become `.neutral`.
    public static func fromAITag(_ raw: String) -> MoodTag {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = MoodTag(rawValue: trimmed) { return exact }
        let lowered = trimmed.lowercased()
        if let match = MoodTag.allCases.first(where: { $0.rawValue.lowercased() == lowered }) {
            return match
        }
        if let match = MoodTag.allCases.first(where: { $0.displayName.lowercased() == lowered }) {
            return match
        }
        // Legacy coercion — should be rare once guided generation uses a Generable enum.
        return .neutral
    }

}
